In [144]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [145]:
x= np.ones(3, int)
print(x)

[1 1 1]


## Q#2: Create y array with elements equal to 0.

In [146]:
y= np.zeros(3, int)
print(y)

[0 0 0]


## Q#3: Add x and y arrays.

In [147]:
print(np.add(x,y))


[1 1 1]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [148]:
print(x.shape)
print(x.ndim)
print(x.size)
x.dtype

(3,)
1
3


dtype('int32')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [149]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [150]:
# write your code here ^_^
z = np.array([[1],[2],[3]])
z

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [151]:
# write your code here ^_^
newArray= np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [152]:
# write your code here ^_^
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [153]:
# write your code here ^_^
print(newArray.transpose())


[[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [154]:
# write your code here ^_^
print(newArray-1)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [155]:
# write your code here ^_^
print(newArray.max())
print(newArray.min())

16
1


## Q#12: Print the first row of "newArray" using indexing.

In [156]:
# write your code here ^_^
print(newArray[0])

[ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [157]:
# write your code here ^_^
print(newArray[newArray==12])

[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [158]:
# write your code here ^_^
newArray[((newArray==13) | (newArray==0))]

array([13])

## Q#15: Change the shape of "newArray" to (9,1).

In [159]:
# write your code here ^_^
#newArray.reshape(9,1)

newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [160]:
# write your code here ^_^
newArray.reshape(3,3)

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

# Well Done 🎉